# -*- coding: utf-8 -*-
"""etl_ibge_rais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhC2_GNKl_nTzoSVyF-uiBu7xpSbUYJQ
"""

"""
Pipeline ETL: Inteligência de Mercado e Expansão Territorial (Varejo Farmacêutico - SP)
Fontes: IBGE (Censo 2022 / Malha Territorial) e RAIS (Base dos Dados / BigQuery)
Modelagem: Esquema Estrela (Kimball) - 1 Tabela Fato e 5 Tabelas Dimensão
"""

import basedosdados as bd
from google.cloud import bigquery
import numpy as np
import pandas as pd
import requests

# Configurações do Projeto no GCP
PROJECT_ID = "projeto-mercado-portfolio"
DATASET_ID = "mercado_sp"


def extrair_demografia_ibge():
  """Coleta população municipal do Censo 2022 via API do IBGE."""
  print("1/5 Extraindo população municipal (Censo 2022)...")
  url_pop = "https://servicodados.ibge.gov.br/api/v3/agregados/9514/periodos/2022/variaveis/93?localidades=N6[N3[35]]"
  res_pop = requests.get(url_pop, timeout=30).json()

  df_pop = pd.DataFrame([
      {
          "id_municipio_ibge": str(item["localidade"]["id"]).strip(),
          "nome_municipio": item["localidade"]["nome"],
          "populacao": int(list(item["serie"].values())[0]),
      }
      for item in res_pop[0]["resultados"][0]["series"]
  ])
  return df_pop


def extrair_hierarquia_regional():
  """Coleta dados de mesorregiões e microrregiões do Estado de SP."""
  print("2/5 Extraindo estrutura regional do IBGE...")
  url_reg = "https://servicodados.ibge.gov.br/api/v1/localidades/estados/35/municipios"
  res_reg = requests.get(url_reg, timeout=30).json()

  df_regioes = pd.DataFrame([
      {
          "id_municipio_ibge": str(item["id"]).strip(),
          "id_microrregiao": str(item["microrregiao"]["id"]),
          "nome_microrregiao": item["microrregiao"]["nome"],
          "id_mesorregiao": str(item["microrregiao"]["mesorregiao"]["id"]),
          "nome_mesorregiao": item["microrregiao"]["mesorregiao"]["nome"],
      }
      for item in res_reg
  ])
  return df_regioes


def extrair_concorrencia_rais(project_id):
  """Consulta estabelecimentos farmacêuticos ativos (CNAE 4771701) no BigQuery."""
  print("3/5 Extraindo dados da RAIS via Base dos Dados (BigQuery)...")
  query_rais = """
    SELECT
        id_municipio,
        cnae_2,
        COUNT(*) AS total_estabelecimentos
    FROM `basedosdados.br_me_rais.microdados_estabelecimentos`
    WHERE ano = 2021
      AND sigla_uf = 'SP'
      AND cnae_2 = '4771701'
    GROUP BY id_municipio, cnae_2
    """
  df_rais = bd.read_sql(query_rais, billing_project_id=project_id, reauth=False)
  df_rais["id_municipio"] = df_rais["id_municipio"].astype(str).str.strip()
  df_rais["total_estabelecimentos"] = pd.to_numeric(
      df_rais["total_estabelecimentos"], errors="coerce"
  ).fillna(0)
  return df_rais


def calcular_metricas_mercado(df_pop, df_regioes, df_rais):
  """Cruza bases e gera métricas de densidade concorrencial e dimensionamento (TAM, SAM, SOM)."""
  print("4/5 Executando engenharia de variáveis (TAM, SAM, SOM)...")
  df_full = df_pop.merge(df_regioes, on="id_municipio_ibge", how="left")
  df_full = df_full.merge(
      df_rais, left_on="id_municipio_ibge", right_on="id_municipio", how="left"
  )

  df_full["total_estabelecimentos"] = (
      df_full["total_estabelecimentos"].fillna(0).astype(int)
  )
  df_full["cnae_2"] = df_full["cnae_2"].fillna("4771701")

  # Lojas por mil habitantes
  df_full["densidade_lojas_mil_hab"] = np.where(
      df_full["populacao"] > 0,
      (df_full["total_estabelecimentos"] / df_full["populacao"]) * 1000,
      0.0,
  )

  # Dimensionamento de Demanda (R$ 850/hab/ano para saúde e higiene pessoal)
  df_full["tam_reais"] = df_full["populacao"] * 850.0
  df_full["sam_reais"] = np.where(
      df_full["populacao"] >= 50000, df_full["tam_reais"], 0.0
  )
  df_full["som_reais"] = df_full["sam_reais"] * 0.04

  return df_full


def estruturar_modelo_kimball(df_full, df_regioes):
  """Estrutura as entidades do esquema estrela (1 fato e 5 dimensões)."""
  print("Estruturando tabelas do modelo estrela (Kimball)...")

  # Dimensões
  dim_municipio = df_full[[
      "id_municipio_ibge",
      "nome_municipio",
      "id_microrregiao",
  ]].drop_duplicates()

  dim_regiao = df_regioes[[
      "id_microrregiao",
      "nome_microrregiao",
      "id_mesorregiao",
      "nome_mesorregiao",
  ]].drop_duplicates()
  dim_regiao["macro_cluster"] = np.where(
      dim_regiao["nome_mesorregiao"].str.contains(
          "Metropolitana", case=False, na=False
      ),
      "Região Metropolitana de SP",
      "Interior & Litoral Paulista",
  )

  dim_cnae = pd.DataFrame([
      {
          "cnae_2": "4771701",
          "nome_cnae": (
              "Comércio varejista de produtos farmacêuticos, sem manipulação de"
              " fórmulas"
          ),
          "divisao_cnae": "Comércio Varejista",
          "setor_estrategico": "Farmácias & Saúde",
      }
  ])

  dim_tempo = pd.DataFrame([{
      "ano": 2021,
      "decada": "2020s",
      "safra_estabelecimentos": "RAIS 2021",
      "safra_demografia": "Censo Demográfico 2022",
  }])

  dim_perfil_socioeconomico = pd.DataFrame([
      {
          "id_perfil": 1,
          "porte_populacional": "Micro (Até 20k hab)",
          "potencial_consumo": "Consumo Local Reduzido",
      },
      {
          "id_perfil": 2,
          "porte_populacional": "Pequeno (20k a 50k hab)",
          "potencial_consumo": "Consumo Emergente",
      },
      {
          "id_perfil": 3,
          "porte_populacional": "Médio (50k a 100k hab)",
          "potencial_consumo": "Polo Microrregional",
      },
      {
          "id_perfil": 4,
          "porte_populacional": "Grande (100k a 500k hab)",
          "potencial_consumo": "Alta Atratividade Comercial",
      },
      {
          "id_perfil": 5,
          "porte_populacional": "Metrópole (Acima de 500k hab)",
          "potencial_consumo": "Hiperconcentrado / Alta Saturação",
      },
  ])

  # Mapeamento de chave na Fato
  condicoes = [
      df_full["populacao"] < 20000,
      df_full["populacao"] < 50000,
      df_full["populacao"] < 100000,
      df_full["populacao"] < 500000,
  ]
  df_full["id_perfil"] = np.select(condicoes, [1, 2, 3, 4], default=5)

  # Fato
  fato_densidade_varejo = pd.DataFrame({
      "id_municipio_ibge": df_full["id_municipio_ibge"],
      "cnae_2": df_full["cnae_2"],
      "ano": 2021,
      "id_perfil": df_full["id_perfil"].astype(int),
      "populacao": df_full["populacao"].astype(int),
      "total_estabelecimentos": df_full["total_estabelecimentos"].astype(int),
      "densidade_lojas_mil_hab": df_full["densidade_lojas_mil_hab"].round(4),
      "tam_reais": df_full["tam_reais"].round(2),
      "sam_reais": df_full["sam_reais"].round(2),
      "som_reais": df_full["som_reais"].round(2),
  })

  return {
      "fato_densidade_varejo": fato_densidade_varejo,
      "dim_municipio": dim_municipio,
      "dim_regiao": dim_regiao,
      "dim_cnae": dim_cnae,
      "dim_tempo": dim_tempo,
      "dim_perfil_socioeconomico": dim_perfil_socioeconomico,
  }


def carregar_no_bigquery(tabelas, project_id, dataset_id):
  """Persiste as tabelas relacionais no Google BigQuery com política WRITE_TRUNCATE."""
  print(f"5/5 Carregando tabelas no BigQuery ({dataset_id})...")
  client = bigquery.Client(project=project_id)

  dataset_ref = bigquery.DatasetReference(project_id, dataset_id)
  client.create_dataset(bigquery.Dataset(dataset_ref), exists_ok=True)
  job_config = bigquery.LoadJobConfig(
      write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE
  )

  for nome_tabela, df in tabelas.items():
    table_id = f"{project_id}.{dataset_id}.{nome_tabela}"
    job = client.load_table_from_dataframe(df, table_id, job_config=job_config)
    job.result()
    print(f"-> Tabela '{nome_tabela}' sincronizada ({len(df)} registros).")


def main():
  print("=" * 60)
  print("Iniciando execução do pipeline ETL de Inteligência de Mercado")
  print("=" * 60)

  df_pop = extrair_demografia_ibge()
  df_regioes = extrair_hierarquia_regional()
  df_rais = extrair_concorrencia_rais(PROJECT_ID)

  df_mercado = calcular_metricas_mercado(df_pop, df_regioes, df_rais)
  modelo = estruturar_modelo_kimball(df_mercado, df_regioes)

  carregar_no_bigquery(modelo, PROJECT_ID, DATASET_ID)

  print("=" * 60)
  print("Pipeline executado com sucesso! Dados disponíveis no BigQuery.")
  print("=" * 60)


if __name__ == "__main__":
  main()